SEED_STUDENTS = [
    # --- informatique ---
    {
        "id": 1,
        "firstName": "Ahmed",
        "lastName": "Ben Salah",
        "email": "ahmed.bensalah@example.com",
        "grade": 15.5,
        "field": "informatique",
    },
    {
        "id": 2,
        "firstName": "Yanis",
        "lastName": "Dubois",
        "email": "yanis.dubois@example.com",
        "grade": 6.5,
        "field": "informatique",
    },
    {
        "id": 3,
        "firstName": "Mei",
        "lastName": "Chen",
        "email": "mei.chen@example.com",
        "grade": 20.0,
        "field": "informatique",
    },
    # --- mathématiques ---
    {
        "id": 4,
        "firstName": "Léa",
        "lastName": "Martin",
        "email": "lea.martin@example.com",
        "grade": 9.0,
        "field": "mathématiques",
    },
    {
        "id": 5,
        "firstName": "Ibrahim",
        "lastName": "Diallo",
        "email": "ibrahim.diallo@example.com",
        "grade": 13.75,
        "field": "mathématiques",
    },
    {
        "id": 6,
        "firstName": "Camille",
        "lastName": "Petit",
        "email": "camille.petit@example.com",
        "grade": 0.0,
        "field": "mathématiques",
    },
    # --- physique ---
    {
        "id": 7,
        "firstName": "Karim",
        "lastName": "Haddad",
        "email": "karim.haddad@example.com",
        "grade": 18.0,
        "field": "physique",
    },
    {
        "id": 8,
        "firstName": "Elena",
        "lastName": "Popescu",
        "email": "elena.popescu@example.com",
        "grade": 11.25,
        "field": "physique",
    },
    {
        "id": 9,
        "firstName": "Thomas",
        "lastName": "Lefevre",
        "email": "thomas.lefevre@example.com",
        "grade": 16.5,
        "field": "physique",
    },
    # --- chimie ---
    {
        "id": 10,
        "firstName": "Sofia",
        "lastName": "Rossi",
        "email": "sofia.rossi@example.com",
        "grade": 12.25,
        "field": "chimie",
    },
    {
        "id": 11,
        "firstName": "Nora",
        "lastName": "Ferreira",
        "email": "nora.ferreira@example.com",
        "grade": 14.0,
        "field": "chimie",
    },
    {
        "id": 12,
        "firstName": "Hugo",
        "lastName": "Bernard",
        "email": "hugo.bernard@example.com",
        "grade": 8.5,
        "field": "chimie",
    },
]